api = "0.8"

[buildpack]
id = "be.rossel.tech.php"
version = "1.0.0"
name = "PHP Buildpack"

[[order]]
  [[order.group]]
  id = "heroku/php"

  [[order.group]]
  id = "be.rossel.tech.php.pdosqlsrv"
  optional = true 

  [[order.group]]
  id = "heroku/procfile"  